### PR TITLE
Coursera socialite provider

### PR DESCRIPTION
**Pull request by davetosh**

### CODE REVIEW

**Comment by DraperStudio** [comment]
Please stop opening and closing PRs, you can just work on one repository.

Apply the StyleCI Patch and I will move the Provider to a separate repository.

**Comment by DraperStudio** [comment]
Moved to it's own repository https://github.com/SocialiteProviders/Coursera and added to Packagist.

**Comment by davetosh** [comment]
Sorry about the multiple PRs. I never realised you can keep committing to the branch in the request and it will automatically update, that is good to know!

**Comment by DraperStudio** [comment]
Could you please remove `pedalred/coursera` from packagist? We keep all providers under the `socialiteproviders/` namespace.

People will still know that you wrote the Provider since you are noted as author in the composer.json

**Comment by davetosh** [comment]
Done.

**Comment by DraperStudio** [comment]
Thanks!

**Comment by davetosh** [comment]
Promise my next PR will be less hassle!

**Pull request closed without merging**
