### PR TITLE
Moves Socialite

### PR DESCRIPTION
**Pull request by bryceadams**
Hope this was done properly - cheers @DraperStudio!

### CODE REVIEW

**Comment by DraperStudio** [comment]
The return value of the `mapUserToObject `-method is missing the `nickname, name, email, avatar`-fields.

If they don't exist just add them with `null` as value.

**Comment by bryceadams** [comment]
Yep, they don't exist. Added `null` for all. Cheers!

**Comment by DraperStudio** [comment]
Thanks, moved the repository and added docs.

https://github.com/SocialiteProviders/Moves
http://socialiteproviders.github.io/providers/moves/

**Comment by DraperStudio** [comment]
Please delete this https://packagist.org/packages/bryceadams/moves-socialite.

We keep all Providers under the same namespace as we note the authors in the composer.json.

**Comment by bryceadams** [comment]
Sorry was waiting for you to merge before deleting. Deleted.

**Comment by DraperStudio** [comment]
No problem, thanks.

**Comment by bryceadams** [comment]
Could you put it up on Packagist @DraperStudio?

**Comment by bryceadams** [comment]
Oh, I just saw it under https://packagist.org/packages/socialiteproviders/moves-socialite

**Pull request closed without merging**
