### PR TITLE
Envato API Two Provider

### PR DESCRIPTION
**Pull request by dennisoderwald**

### CODE REVIEW

**Comment by DraperStudio** [comment]
Thanks for the Provider, I will take a closer look next week. Currently have no computer with me.

**Comment by dennisoderwald** [comment]
Ok fine. :)

**Comment by AndyWendt** [comment]
I'll take a look shortly!

**Comment by dennisoderwald** [comment]
Now with email address and username support. Please verify my way of doing.

**Comment by DraperStudio** [comment]
Could you also download and apply the StyleCI patch, please.

**Comment by dennisoderwald** [comment]
Hmm.. in commit 06fd97e, I had always commited?!

**Comment by DraperStudio** [comment]
You can download the patch file here https://styleci.io/commits/e588c6967fb47caca12facf27670eae6bf6bf783

After you've downloaded the patch just do the following and you should be set.
`git apply /path/to/patch.txt`

**Comment by dennisoderwald** [comment]
> error: patch failed: Envato/src/EnvatoExtendSocialite.php:1
> error: Envato/src/EnvatoExtendSocialite.php: patch does not apply
> error: patch failed: Envato/src/Provider.php:1
> error: Envato/src/Provider.php: patch does not apply

**Comment by DraperStudio** [comment]
Great, Andy should take a closer look later. Thanks for the work so far.

**Comment by AndyWendt** [comment]
I will by this weekend.

**Comment by DraperStudio** [comment]
The Envato provider is now available here https://github.com/SocialiteProviders/Envato and through packagist. I will add a docs page later.

Thanks for the Provider.

**Pull request closed without merging**
