### PR TITLE
Steam Provider

### PR DESCRIPTION
**Pull request by eklundchristopher**
Unfortunately, Steam doesn't offer an OAuth solution, but they do offer OpenID authentication. I don't know whether this qualifies or not (as it is a bit of a workaround), but thought I'd give it a shout.

Also worth noting that the client_id has to be set to null (or any value for that matter), client_secret contains the API key, and the redirect value contains the redirect url just as any other service.

https://steamcommunity.com/dev

### CODE REVIEW

**Comment by DraperStudio** [comment]
Will take a look at this soon.

**Comment by DraperStudio** [comment]
@eklundchristopher Could you add more details to the README on how to setup the credentials and urls? Will merge it then.

**Comment by eklundchristopher** [comment]
@DraperStudio Absolutely. Will do in a little bit.

**Comment by DraperStudio** [comment]
Will move it to its own repository in a few hours.

**Comment by DraperStudio** [comment]
@eklundchristopher https://github.com/SocialiteProviders/Steam

**Pull request closed without merging**
