### PR TITLE
Adding SharePoint Provider

### PR DESCRIPTION
**Pull request by kaiten65**
This provider will allow people to work with API from within SharePoint.

### CODE REVIEW

**Comment by DraperStudio** [comment]
I will move this to it's own repository tomorrow.

**Comment by DraperStudio** [comment]
https://github.com/SocialiteProviders/SharePoint

Thanks!

**Comment by kaiten65** [comment]
Some changes need to be made to the instructions. I will update the README.md

**Comment by DraperStudio** [comment]
Which changes? The README is the same as for all providers.

**Comment by kaiten65** [comment]
since sharepoint instance url alternates from installation, they would need to provide their particular url to connect to their own sharepoint instance if not the authentication will not work.

Sent from Nine

**Comment by DraperStudio** [comment]
Ok, send a PR to the SharePoint Repo then.

**Pull request closed without merging**
